config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get 'welcome/index'
  get "/contact" => "welcome#contact"


  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}


  root to: 'welcome#index'

  namespace :api, defaults: {format: :json} do
    scope '/v1' do
      scope '/user' do
        get '/'     => 'requests#ldap_user'
        get '/:id'  => 'requests#ldap_user'
        get '/new'  => 'requests#ldap_user'
      end

      scope '/group' do
        get '/'     => 'requests#ldap_group'
        get '/:id'  => 'requests#ldap_group'
        get '/new'  => 'requests#ldap_group'
      end

      scope '/request' do
        get '/'                   => 'requests#index'
        get '/schema'             => 'requests#ldap_schema_list'
        get '/schema/:schema'     => 'requests#ldap_schema_attributes'
        get '/:id/schema'         => 'requests#ldap_schema_list'
        get '/:id/schema/:schema' => 'requests#ldap_schema_attributes'
        get '/:id'                => 'requests#ldap_attributes'

      end
    end


    resources :ldap_users, only: [:index, :show, :create, :update, :destroy]
    resources :ldap_groups, only: [:index, :show, :create, :update, :destroy]

  end

  get "*path.html" => "application#index", :layout => 0
  get "*path" => "application#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by <a href="https://www.linkedin.com/in/georgekaraszi">George Karaszi</a>
  </small>
  <nav>
    <ul>
      <% if Rails.env.development? %>
        <li><%= link_to 'JSpecs', jasmine_rails_path, :target =>"_self"%></li>
      <% end %>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", contact_path, :target =>"_self" %></li>
      <% if user_signed_in? %>
           <li><%= link_to "Log out", '/logout', :method => :delete %></li>
      <% else %>
          <li><%= link_to "Log in", '/login'%></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "LDAP Web-Manager", root_path, id: "logo", :target =>"_self" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Home", root_path, :target =>"_self" %></li>
            <li><%= link_to "Manage Groups", '/ldap_groups' %></li>
            <li><%= link_to "Manage Users", '/ldap_users' %></li>
            <li><%= link_to "Log out", '/logout', :method => :delete %></li>
        <% else %>
            <li><%= link_to "Log in", 'login' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>CSWebAdmin</title>
  <base href="/">
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body ng-app="ldapManager">

<%= render 'layouts/header' %>
<div class="container">
  <div class="content">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div> <!-- content -->
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div> <!-- container -->



</body>
</html>